services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  backend-auth:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - '3030:3030'
    depends_on:
      - mongo
    environment:
      - HOST=0.0.0.0
      - PORT=3030
      - MONGO_URL=mongodb://mongo:27017/test
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}


