###

GET http://localhost:3030/api/users

###
GET http://localhost:3030/api/users?text=test2

###

POST http://localhost:3030/api/register
Content-Type: application/json

{
  "name": "Renato2",
  "email": "renatinho2@outlook.com.br",
  "password": "maça"
}

###
DELETE http://localhost:3030/api/users/67d1c573bd3101386bd3ac39