###

GET http://localhost:3030/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjdkMWUwMjcyYTM4OWI3M2M0OWI3MWI1IiwibmFtZSI6IlJpY2FyZG8iLCJlbWFpbCI6ImF0YWtpYW1hQG91dGxvb2suY29tLmJyIn0sImlhdCI6MTc0MjU4MDAxNiwiZXhwIjoxNzQyNTgwOTE2fQ._NCRt0u9plPPXwZJ7ocFu3iGi9sE12qZdOJywxL9r3w

###
GET http://localhost:3030/api/users?text=test2

###

POST http://localhost:3030/api/users
Content-Type: application/json

{
  "name": "Renato3",
  "email": "renatinho2@outlook.com.br",
  "password": "maça"
}

###
DELETE http://localhost:3030/api/users/67ddacbc465746f4ed985f5c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjdkMWUwMjcyYTM4OWI3M2M0OWI3MWI1IiwibmFtZSI6IlJpY2FyZG8iLCJlbWFpbCI6ImF0YWtpYW1hQG91dGxvb2suY29tLmJyIn0sImlhdCI6MTc0MjU4MDk1MywiZXhwIjoxNzQyNTgxODUzfQ.c74XqwmHTiJOelHc-lKD9zuGETnopErqZo9PRPhQwV0

###  LOGIN
POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
  "email": "atakiama@outlook.com.br",
  "password": "batata"
}

### REFRESH
POST http://localhost:3030/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjdkMWUwMjcyYTM4OWI3M2M0OWI3MWI1IiwibmFtZSI6IlJpY2FyZG8iLCJlbWFpbCI6ImF0YWtpYW1hQG91dGxvb2suY29tLmJyIn0sImlhdCI6MTc0MjU4MzAyNSwiZXhwIjoxNzQzMTg3ODI1fQ.XjrMK2iSurQ4P07mbSbcExbBy0Qz5T_SzassC-V4lyM"
}